pub const WORDS: [&str; 256] = [
    "apple", "arch", "arrow",
    "azure", "beacon", "berry", "blade",
    "blaze", "cedar", "charm", "cinder",
    "cloud", "coral", "crown",
    "dream", "drift",
    "ember", "fable", "flame", "flash",
    "frost", "glade", "gleam", "glide",
    "grove", "haven", "heart", "horizon",
    "iris", "jade", "jewel",
    "lance", "light", "lunar",
    "maple", "meadow", "mist", "moon",
    "nectar", "north", "nova",
    "oasis", "ocean", "olive",
    "orbit", "orchid",
    "pearl", "petal", "phoenix", "pine",
    "pixel", "prism", "pulse", "quartz",
    "quest", "raven", "ridge",
    "river", "rose", "ruby", "sage",
    "sapphire", "silver", "sky",
    "solar", "spark", "spirit", "star",
    "storm", "stream", "swift",
    "thorn", "thunder", "tide", "tiger",
    "tower", "trace", "twilight",
    "unity", "valley", "vapor", "velvet",
    "vertex", "violet", "vision", "vortex",
    "wave", "whisper", "willow", "wind",
    "winter", "wisdom", "wonder", "zenith",
    "amber", "anchor", "arctic",
    "atlas", "aurora", "autumn", "balance",
    "bloom", "bolt", "brave", "breeze",
    "bridge", "bright", "bronze", "canyon",
    "castle", "cipher", "citrus", "cliff",
    "cobalt", "comet", "compass", "cosmic",
    "crater", "crimson", "dawn",
    "desert", "diamond", "disco", "dusk",
    "eagle", "earth", "eclipse", "emerald",
    "empire", "falcon", "fern", "fiddle",
    "field", "fire", "fjord", "forest",
    "forge", "fossil", "fountain", "freedom",
    "galaxy", "garden", "ghost", "glacier",
    "golden", "granite", "gravity", "harbor",
    "harvest", "hawk", "helix", "hero",
    "highland", "honey", "hunter", "ice",
    "infinity", "island", "jasper", "journey",
    "passion", "pathway", "peace", "pegasus",
    "penguin", "phantom", "photon", "pirate",
    "planet", "plasma", "platinum", "pluto",
    "polar", "portal", "power", "prime", "quick",
    "rabbit", "radar", "rainbow", "rapid",
    "realm", "rebel", "reef", "relic",
    "rider", "rocket", "royal", "saber",
    "sacred", "safari", "sailor", "sandstone",
    "saturn", "scarlet", "scout", "season",
    "secret", "serene", "shark", "shield",
    "shrine", "signal", "silk", 
    "snow", "sonic", "soul", "south",
    "space", "sphere", "spring", "steel",
    "stone", "summer", "sunbeam", "sunrise",
    "sunset", "sword", "tempest", "temple",
    "terra", "titan", "torch", "treasure",
    "tree", "tribal", "trinity", "triumph",
    "tropic", "turbo", "turtle", "unicorn",
    "universe", "urban", "valiant", "venture",
    "venus", "verdant", "victory", "viking",
    "voyage", "warrior", "water", "west",
    "whale", "wildfire", "wolf", "wyvern",
    "xenon", "yacht", "yellow", "youth",
    "zeal", "zebra", "zephyr", "zinc",
];
